#pragma once
#include "../../../IceFlow_Config.h"

#define MSH_PANEL_WIDTH (TFT_DISPLAY_WIDTH - 72)
#define MSH_PANEL_HEIGHT 40
#define MSH_PANEL_X 1
#define MSH_PANEL_Y 0

#define TEMPERATURE_PANEL_WIDTH (TFT_DISPLAY_WIDTH - 72)
#define TEMPERATURE_PANEL_HEIGHT 38
#define TEMPERATURE_PANEL_X 1
#define TEMPERATURE_PANEL_Y (TFT_DISPLAY_HEIGHT - TEMPERATURE_PANEL_HEIGHT)


#define SIDEBAR_WIDTH 69
#define SIDEBAR_PUSH_X (TFT_DISPLAY_WIDTH - SIDEBAR_WIDTH)
#define SIDEBAR_PUSH_Y 0
#define SIDEBAR_Y 0
#define SIDEBAR_HEIGHT TFT_DISPLAY_HEIGHT

#define CP_NORMAL_WIDTH (TFT_DISPLAY_WIDTH - SIDEBAR_WIDTH)
#define CP_NORMAL_HEIGHT (TFT_DISPLAY_HEIGHT - TEMPERATURE_PANEL_HEIGHT - MSH_PANEL_HEIGHT)
#define CP_NORMAL_X 0
#define CP_NORMAL_Y (MSH_PANEL_HEIGHT)