#pragma once

enum ControlCommands {
	CC_NO_CMD = -1,
	CC_START_OTA,
	CC_REQUEST_NET_STATUS,
	CC_START_TIME_UPATES,
	CC_STOP_TIME_UPDATES,
	CC_START_TEMPERATURE_STREAM,
	CC_STOP_TEMPERATURE_STREAM,
	CC_START_MANUAL_HEAT,
	CC_START_REFLOW,
	CC_START_AUTOTUNE,
	CC_REQUEST_OVEN_STATUS,
};