#pragma once

enum STARSIDE_COMMANDS {
	STARSIDE_CMD_NO_COMMAND = 0,
	STARSIDE_CMD_BEGIN_OTA,
	STARSIDE_CMD_DELETE_TOUCH_CALIBRATION,

	STARSIDE_CMD_START_MANUAL_PREHEAT,
	STARSIDE_CMD_START_REFLOW,

	//STARSIDE_CMD_LOAD_HOME_SCREEN,
	//STARSIDE_CMD_LOAD_ABOUT_SCREEN,
	STARSIDE_CMD_RESTART
};