#pragma once

enum SCREEN_UPDATE_KEYS {
	suk_No_Key = -1,
	suk_Device_Name,
	suk_Network_Name,
	suk_Local_IP_Address,
	suk_Network_Connected,
	suk_Network_Started,
	suk_OTA_Progress,
	suk_OTA_Complete,
	suk_DateTime,
	suk_PrimaryTemperature,
	suk_SecondaryTemperature,
	suk_TertiaryTemperature,
	suk_TemperatureStreamStarted,
	suk_Oven_Stopped,
	suk_Emergency_Oven_Stopped,
	suk_Oven_Manual_On,
	suk_Oven_Reflow_On,
	suk_Oven_AutoTune_On,
	suk_Oven_AutoTune_Complete,
	suk_Oven_Heaters_On,
	suk_Oven_Heaters_Off,
	suk_Reflow_StageComplete_PreHeat,
	suk_Reflow_StageComplete_Soak,
	suk_Reflow_StageComplete_Ramp,
	suk_Reflow_StageComplete_Reflow,
	suk_Reflow_StageComplete_Cooling,
	suk_Reflow_Complete
};