#pragma once

enum DISPLAY_COMMANDS {
	DISPLAY_COMMAND_CHANGE_SCREEN = 0,
	DISPLAY_COMMAND_UPDATE_VALUE,

	DISPLAY_COMMAND_NO_COMMAND
};

enum DISPLAY_UPDATE_KEYS {
	DISPLAY_UPDATE_KEY_NO_KEY = 0,

	DISPLAY_UPDATE_KEY_OTA_STARTING,
	DISPLAY_UPDATE_KEY_OTA_PROGRESS_UPDATE,
	DISPLAY_UPDATE_KEY_OTA_COMPLETE,
	DISPLAY_UPDATE_KEY_WIFI_SSID,
	DISPLAY_UPDATE_KEY_WIFI_LOCAL_IP,
	DISPLAY_UPDATE_KEY_WIFI_STATUS_CHANGED,

	DISPLAY_UPDATE_KEY_PRIMARY_TEMPERATURE,
	DISPLAY_UPDATE_KEY_SECONDARY_TEMPERATURE,
};

enum DISPLAY_SCREEN_TYPES {
	DISPLAY_SCREEN_TYPE_NO_SCREEN = 0,
	DISPLAY_SCREEN_TYPE_OTA_SCREEN,
	DISPLAY_SCREEN_TYPE_SPLASH_SCREEN,
	DISPLAY_SCREEN_TYPE_MAIN,
	//DISPLAY_SCREEN_TYPE_HOME_SCREEN,
	//DISPLAY_SCREEN_TYPE_WEBSERVER,
	//DISPLAY_SCREEN_TYPE_ABOUT_SCREEN,
	//DISPLAY_SCREEN_TYPE_DEBUG_SCREEN
};