#pragma once

#define __DEVICE_NAME__ "IceFlow"
#define __DEVICE_VERSION__ "0.1"

// Task priorites and core assignments
#define STACK_SIZE (ESP_TASK_MAIN_STACK) // Stack size for each new thread

#define OVEN_CONTROLLER_PRIORITY tskIDLE_PRIORITY+18
#define WEB_SERVER_PRIORITY tskIDLE_PRIORITY+10
#define OTA_PRIORITY tskIDLE_PRIORITY+15
#define DISPLAY_MANAGER_PRIORITY tskIDLE_PRIORITY+10

#define OVEN_CONTROLLER_CORE 0
#define WEBSERVER_CORE	1
#define OTA_CORE	1
#define DISPLAY_MANAGER_CORE 0


// NETWORK
#define NETWORK_WAIT_TIME_PER_TRY 30 //seconds
#define NETWORK_TRY_TIMES 3

#define WIFI_PREFERENCES_FILENAME "wifi"
#define WIFI_PREFERENCES_SSID_KEY "ssid"
#define WIFI_PREFERENCES_PASWORD_KEY "password"

//Webpages
#define WEBPAGE_NETWORK "/net.htm"

//Hardware connections
//#define PROBE_A_CS_PIN 12
//#define PROBE_B_CS_PIN 13
#define PROBE_CLK 27
#define PROBE_MISO 14


#define SSR_OVEN_HEATERS 26
#define RELAY_CONVECTION_FAN 25

//Hardware definintions
#define RELAY_OFF LOW
#define RELAY_ON HIGH

//Profile stuff
#define PROFILE_MANAGER_FILENAME "PM"
#define CURRENT_LOADED_PROFILE "CLP"
#define PROFILE_SPIFFS_FILE_DIRECTORY "/profiles"
#define MINIUM_OVEN_TEMPERATURE_FOR_FAN 50

#define OVEN_MAXIMUM_TEMPERATURE 250

#define TEMPERATURE_DISPLAY_REFRESH_RATE 100

#define TFT_DISPLAY_WIDTH 320
#define TFT_DISPLAY_HEIGHT 240

#define GLOBAL_TEXT_COLOR 0xCE59
#define GLOBAL_PANEL_HCOLOR 0x5AEB
#define GLOBAL_PANEL_BGCOLOR 0x738E
#define GLOBAL_BOX_BORDER_COLOR 0x9CD3
#define GLOBAL_BOX_DROP_SHADOW 0x4208

#define AA_FONT_10PT "SegoeUI-10"
#define AA_FONT_14PT "SegoeUI-14"
#define AA_FONT_18PT "SegoeUI-18"
#define AA_FONT_20PT "SegoeUI-20"